# Generated by Django 5.2.15 on 2026-06-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryVisaRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100, unique=True)),
                ('visa_required', models.CharField(blank=True, max_length=50, null=True)),
                ('days_without_visa', models.IntegerField()),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
