# Generated by Django 5.2.15 on 2026-06-06 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('eu_name', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Country group',
                'verbose_name_plural': 'Country groups',
            },
        ),
        migrations.CreateModel(
            name='VisaRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_without_visa', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisaStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CountryVisaRule',
        ),
        migrations.AddField(
            model_name='country',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='countries', to='main.groups'),
        ),
        migrations.AddField(
            model_name='visarule',
            name='destination_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_rules_to', to='main.country'),
        ),
        migrations.AddField(
            model_name='visarule',
            name='passport_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_rules_from', to='main.country'),
        ),
        migrations.AddField(
            model_name='visarule',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visa_rules', to='main.visastatus'),
        ),
        migrations.AlterUniqueTogether(
            name='visarule',
            unique_together={('passport_country', 'destination_country')},
        ),
    ]
